最終課題/Feedページ/記事一覧
shinonome-inc/mobile_takahiro2_basic_flutter pull request #14
Opened 2023-06-08 10:55 UTC by taka392

## 概要
Feed Pageの記事一覧データ表示を作成しました。

## CLIENT_IDとCLIENT_SECRET

## 実装した内容
記事一覧データ表示

## UI
![スクリーンショット 2023-06-08 19 54 19](https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/88756420/992a1697-8987-4735-b08d-3bf0e5e59c75)

## 動作確認

## 参考
https://www.notion.so/Feed-cad03fac99414a619d6ddd08b37563b7
https://qiita.com/abouch/items/90107b330bb126a6f742

## その他

2023-06-10 02:29 UTC, KobayashiYoh requested changes
コメントしました。

2023-06-10 02:29 UTC, KobayashiYoh commented on qiita_app/lib/pages/navigation/article_list_page.dart
> +      debugShowCheckedModeBanner: false,
`MaterialApp`は1つのアプリにつき1つ定義するのが一般的です。
`main.dart`で既に記述されているため、こちらの`MaterialApp`は削除しちゃってください。

2023-06-10 02:29 UTC, KobayashiYoh commented on qiita_app/lib/pages/navigation/article_list_page.dart
> +          ),
`AppBarの下に表示されている検索バーの実装もお願いします。`

2023-06-10 03:01 UTC, taka392 commented on qiita_app/lib/pages/navigation/article_list_page.dart
> +  final String id;
ディレクトリ構造整理しようと思ってたので、すごい助かります！ありがとうございます

2023-06-14 12:16 UTC, KobayashiYoh requested changes
先ほどDawnでお話しした点についてコメントしました。

2023-06-14 12:16 UTC, KobayashiYoh commented on qiita_app/lib/components/search_bar.dart
> +  final Function(List<Article>) onArticlesChanged; // 追加
```
'SearchBar' isn't a function. (Documentation)  Try correcting the name to match an existing function, or define a method or function named 'SearchBar'.
The name 'SearchBar' is defined in the libraries 'package:flutter/src/material/search_anchor.dart (via package:flutter/material.dart)' and 'package:qiita_app/components/search_bar.dart'. (Documentation)  Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.
```
上記のようなエラーが表示されています。
material.dartに元々定義されているSearchBarと名前が重複している影響でビルドできないため、別の名前を考慮する必要がありそうですね。

2023-06-14 13:11 UTC, KobayashiYoh commented on qiita_app/lib/pages/navigation/article_list_page.dart
> +  final String id;
ディレクトリ構造かなり綺麗になりましたね！
整理されていて見やすいです👍

2023-06-14 15:00 UTC, KobayashiYoh requested changes
コメントしました。

2023-06-14 15:00 UTC, KobayashiYoh commented on qiita_app/lib/components/default_appbar.dart
> +      title: Text(
figmaと比べて影が濃すぎますね。

2023-06-14 15:03 UTC, KobayashiYoh commented
最初と比べてかなり良くなってきています👍
今回の課題に限らず、レビューを出す前にfigmaのデザインを再現できているか必ず確認してみてください。
再現が難しい場合はPGritやDawnにて質問してください。
講師陣でサポートします。

2023-06-14 16:10 UTC, taka392 commented
![スクリーンショット 2023-06-15 1 10 30](https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/88756420/48b7e1e3-821d-4e32-8245-f16db91ad919)

2023-06-14 16:12 UTC, taka392 commented
titleプロパティからbottomプロパティに変更して解決しました。

2023-06-14 16:13 UTC, taka392 commented on qiita_app/lib/components/default_appbar.dart
> +      title: Text(
影を訂正しました

2023-06-14 16:13 UTC, taka392 commented on qiita_app/lib/models/article.model.dart
> +      likesCount: json['likes_count'] ?? 0,
修正します

2023-06-15 14:57 UTC, KobayashiYoh requested changes
コメントしました。
3つ分の課題を1回のプルリクで進めているため、どうしても修正箇所が多くなってしまっています。
ご了承ください。

2023-06-15 14:57 UTC, KobayashiYoh commented on qiita_app/lib/components/default_appbar.dart
> +      title: Text(
SearchAppBarの方は良くなりましたね👍
ただ、SearchAppBarだけでなく、DefaultAppBarの影の修正もしてください。

2023-06-15 14:57 UTC, KobayashiYoh commented on qiita_app/lib/components/search_app_bar.dart
> +  final Function(List<Article>) onArticlesChanged; // 追加
最初と比べて見違えるぐらいUIが整ってきましたね！
ただ、入力したテキストが上に偏っているため、そこを修正すれば更にレベルの高いUIに仕上がると思います（もったいない！）。

ちなみに、StatelessWidgetじゃなくてStatefulWidgetにした理由ってあったりしますか？

2023-06-15 14:57 UTC, KobayashiYoh commented on qiita_app/lib/models/article.model.dart
> +      likesCount: json['likes_count'] ?? 0,
createdAtやlikesCountで??演算子を利用した理由とかってありますか？
例えば、createdAtの値はstringで固定のため、nullの処理を行う必要はない気がします。
Qiita APIの公式ドキュメントを読むことで返り値の型など様々な情報を得ることができます。
https://qiita.com/api/v2/docs

<img width="417" alt="スクリーンショット 2023-06-15 23 46 00" src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82624334/ef181ad3-fe99-4906-b1e7-659717829266">

2023-06-15 14:57 UTC, KobayashiYoh commented on qiita_app/lib/pages/feed_page.dart
> +  }
検索の際のローディングが表示されるようにしましょう。

2023-06-15 14:57 UTC, KobayashiYoh commented on qiita_app/lib/pages/feed_page.dart
> +              );
データ取得のエラーだけでなく、検索結果が0件だった場合のエラー画面も実装してください。

2023-06-15 14:57 UTC, KobayashiYoh commented on qiita_app/lib/pages/navigation/feed_page.dart
> -}
ディレクトリ構造が以前よりわかりやすくなりましたね✨

2023-06-15 15:00 UTC, KobayashiYoh commented
修正した箇所は返信いただけると助かります🙏

2023-06-16 01:01 UTC, taka392 commented on qiita_app/lib/pages/navigation/article_list_page.dart
> +              Text('いいね:${article.likesCount.toString()}'),
「ユーザー名」から「ユーザーID」への変更完了しました。
テキスト間の余白変更完了しました

2023-06-16 01:02 UTC, taka392 commented on qiita_app/lib/pages/navigation/article_list_page.dart
> +      debugShowCheckedModeBanner: false,
Material Appの削除完了しました

2023-06-16 01:02 UTC, taka392 commented on qiita_app/lib/pages/navigation/article_list_page.dart
> +          ),
Todo：検索バー

2023-06-16 01:03 UTC, taka392 commented on qiita_app/lib/pages/navigation/feed_page.dart
> -}
ありがとうございます！！！！！！

2023-06-16 01:35 UTC, taka392 commented on qiita_app/lib/components/default_appbar.dart
> +      title: Text(
6/16 DefaultAppBarの影の修正しました

2023-06-16 01:56 UTC, taka392 commented on qiita_app/lib/components/search_app_bar.dart
> +  final Function(List<Article>) onArticlesChanged; // 追加
入力したテキストが上に偏っている現象修正しました。
Stlではなく、stfにした理由は、小要素であるsearch_appで状態を管理したかったからです。コールバック関数の呼び出し？を行っております。https://note.com/hatchoutschool/n/n6f4317f41741

2023-06-16 01:57 UTC, taka392 commented on qiita_app/lib/models/article.model.dart
> +      likesCount: json['likes_count'] ?? 0,
修正しました。

2023-06-16 01:59 UTC, taka392 commented on qiita_app/lib/components/search_app_bar.dart
> +  final Function(List<Article>) onArticlesChanged; // 追加
入力したテキストが上に偏っている現象修正しました。
StatelessWidgetではなく、StatefulWidgetにした理由は、
小要素で状態を管理したかったからです。コールバック関数の呼び出し？を行っております。
[https://note.com/hatchoutschool/n/n6f4317f41741](url)

2023-06-16 02:45 UTC, taka392 commented on qiita_app/lib/components/search_app_bar.dart
> +  final Function(List<Article>) onArticlesChanged; // 追加
もしかして、stlでも実装できますか？

2023-06-16 02:58 UTC, taka392 commented on qiita_app/lib/pages/feed_page.dart
> +  }
修正しました。

2023-06-16 02:58 UTC, taka392 commented on qiita_app/lib/pages/feed_page.dart
> +  }
修正しました。

2023-06-16 04:29 UTC, taka392 commented on qiita_app/lib/pages/feed_page.dart
> +              );
検索結果が0件の場合のエラー修正しました。

2023-06-16 11:52 UTC, KobayashiYoh requested changes
追加でコメントしました。

2023-06-16 11:52 UTC, KobayashiYoh commented on qiita_app/lib/pages/feed_page.dart
> +      },
こういった条件分岐は一箇所で済ませた方が良いと思われます。
こことFutureBuilderの二箇所で条件分岐を行なっているため、かなりコードが複雑になってしまっています。

CircularProgressIndicator()が3回も登場していますね。

2023-06-16 11:52 UTC, KobayashiYoh commented on qiita_app/lib/pages/feed_page.dart
> +  }
この関数名にした理由とかってありますか？

2023-06-16 11:52 UTC, KobayashiYoh commented on qiita_app/lib/pages/feed_page.dart
> +  }
最初に記事を取得する際もローディングを表示したいですね。
現在だとNoMatchクラスが最初に表示されてしまっています。

2023-06-16 11:52 UTC, KobayashiYoh commented on qiita_app/lib/pages/feed_page.dart
> +                    );
ここでNetworkErrorクラスを表示すればOfflineBuilderを使用する必要はないと思ったのですが、いかがでしょうか。
新しいパッケージを自分で調べて使いこなせている点は素晴らしいです✨

2023-06-16 12:35 UTC, KobayashiYoh commented on qiita_app/lib/components/search_app_bar.dart
> +  final Function(List<Article>) onArticlesChanged; // 追加
`stl`に変えて動かしてみてください。

2023-06-16 12:37 UTC, KobayashiYoh commented on qiita_app/lib/components/search_app_bar.dart
> +  final Function(List<Article>) onArticlesChanged; // 追加
UIコンポーネントで状態管理を行うのはあまり好ましくない気がします。
PageとUIコンポーネントの2箇所で状態管理を行うよりも、Pageで一括して状態管理を行った方が管理しやすいと思ったのですが、いかがでしょうか。

2023-06-16 12:39 UTC, KobayashiYoh commented on qiita_app/lib/pages/feed_page.dart
> +  }
ちょっと惜しいです！
呼び出される時と呼び出されない時がありますね。

2023-06-16 12:40 UTC, KobayashiYoh commented on qiita_app/lib/pages/feed_page.dart
> +              );
いいですね👍

2023-06-17 01:40 UTC, taka392 commented on qiita_app/lib/pages/feed_page.dart
> +  final List<Article>? articles;
別のファイルで共有化修正しました。
1つのファイルに１つのクラス修正しました。

2023-06-17 01:42 UTC, taka392 commented on qiita_app/lib/pages/feed_page.dart
> +  }
_getLoadingに変更しました。

2023-06-17 01:50 UTC, taka392 commented on qiita_app/lib/pages/feed_page.dart
> +                    );
難しく考えすぎてました。確かにそうですね！！
OfflineBuilderを使用せずに、snapshot.errorのときに、NetworkErrorを表示するように修正しました。

2023-06-17 02:27 UTC, taka392 commented on qiita_app/lib/pages/feed_page.dart
> +  }
最初の記事を取得する際にローディングが表示されるように修正しました

2023-06-17 02:27 UTC, taka392 commented on qiita_app/lib/pages/feed_page.dart
> +      },
条件分岐を修正しました

2023-06-17 02:40 UTC, taka392 commented on qiita_app/lib/components/search_app_bar.dart
> +  final Function(List<Article>) onArticlesChanged; // 追加
メモ：子ウィジェットで状態を管理するのではなく、関数を渡して、親ウィジェットで状態を管理する

2023-06-17 02:58 UTC, taka392 commented on qiita_app/lib/components/search_app_bar.dart
> +  final Function(List<Article>) onArticlesChanged; // 追加
stlへの変更&Pageで一括して状態管理できるように修正しました

2023-06-17 02:59 UTC, taka392 commented on qiita_app/lib/pages/feed_page.dart
> +  }
修正しました

2023-06-17 06:08 UTC, KobayashiYoh commented on qiita_app/lib/pages/feed_page.dart
> +  }
完璧です✨

2023-06-17 06:12 UTC, KobayashiYoh commented on qiita_app/lib/pages/feed_page.dart
> +      },
だいぶシンプルになりましたね。

2023-06-17 06:19 UTC, KobayashiYoh requested changes
2点コメントしました。
1点は修正お願いします。
もう1点は修正任意です。

2023-06-17 06:19 UTC, KobayashiYoh commented on qiita_app/lib/components/default_appbar.dart
> +  final String text;
細かいですが、ここのファイル名は`default_app_bar.dart`が適切だと思われます。
修正お願いします。

2023-06-17 06:19 UTC, KobayashiYoh commented on qiita_app/lib/pages/feed_page.dart
> +  }
自分だったら以下のように実装します。
```
void _setLoading(bool value) {
    setState(() {
        showLoadingIndicator = value;
    });
}
```

メソッド名に関しては、以下を参考にしてみてください。
https://qiita.com/KeithYokoma/items/2193cf79ba76563e3db6

修正は任意です。

2023-06-17 06:27 UTC, taka392 commented on qiita_app/lib/components/default_appbar.dart
> +  final String text;
修正しました

2023-06-17 06:38 UTC, taka392 commented on qiita_app/lib/pages/feed_page.dart
> +  }
修正しました
確かに、引数で渡してあげたほうが楽ですね！

2023-06-17 06:51 UTC, KobayashiYoh commented
UIもコードもかなり綺麗になりましたね✨
このローディングのUIだけ修正できたらOKです。
<img src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82624334/422e1741-8c3b-41f6-aed7-9012d33feebd" width="300">

2023-06-17 06:56 UTC, taka392 commented
ローディング修正しました

2023-06-17 07:00 UTC, KobayashiYoh approved these changes

2023-06-17 07:00 UTC, KobayashiYoh commented
LGTMです！
修正お疲れ様です！

2023-06-17 07:01 UTC, merged

2023-06-17 07:15 UTC, MiyuSato commented
2次レビューもLGTMです！お疲れ様でした！