Oauth2
shinonome-inc/mobile_takahiro2_basic_flutter pull request #24
Opened 2023-06-26 08:16 UTC by taka392

## 概要

## CLIENT_IDとCLIENT_SECRET

## 実装した内容

## UI

## 動作確認

## 参考

## その他

2023-06-26 08:40 UTC, taka392 commented
上記の動画は、アクセストークンを保有していた場合

2023-06-28 02:25 UTC, iu-yusei reviewed
@taka392 
認証系の動作は問題ないと思います！
いくつかコメントしました！

2023-06-28 02:25 UTC, iu-yusei commented on qiita_app/lib/services/repository.dart
> +  //アクセストークンをSharedPreferencesを使用することで、データを永続的に保存することができる。
SharedPreferencesでうまくローカルにトークンを保存＆取得できていますね！
お見事です！
<img width="833" alt="image" src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/78660150/f9e379b0-32d9-430e-9e8f-d710848ba1ab">

2023-06-28 02:27 UTC, iu-yusei requested changes
いくつかコメントしましたー

2023-06-28 09:21 UTC, taka392 commented on qiita_app/.gitignore
> +/lib/qiita_auth_key.dart
修正しました。

2023-06-28 09:22 UTC, taka392 commented
<img width="635" alt="スクリーンショット 2023-06-28 18 21 12" src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/88756420/785abd7b-4ce3-4731-af39-a81c2080ae81">
--------------------------------------------
上記のエラーが発生していますが、無視で大丈夫でしょうか？

2023-06-29 01:57 UTC, iu-yusei commented
> <img alt="スクリーンショット 2023-06-28 18 21 12" width="635" src="https://user-images.githubusercontent.com/88756420/249417703-785abd7b-4ce3-4731-af39-a81c2080ae81.png">
> 上記のエラーが発生していますが、無視で大丈夫でしょうか？



> <img alt="スクリーンショット 2023-06-28 18 21 12" width="635" src="https://user-images.githubusercontent.com/88756420/249417703-785abd7b-4ce3-4731-af39-a81c2080ae81.png">
> 上記のエラーが発生していますが、無視で大丈夫でしょうか？

gitのcacheだけでなく、`qiita_auth_key.dart`自体を削除しましたか？
削除していない状態で、このエラーが出ているのであれば、無視してしまって大丈夫だと思います！

2023-06-29 02:16 UTC, taka392 commented
cacheのみ削除を行いqiita_auth_key.dartは残っている状況です。

2023-06-29 02:51 UTC, iu-yusei commented
修正は任意ですが、意図しない挙動が発生してしまう可能性があるので、スワイプバック機能は無効化できると良いと思います！

https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/78660150/4cd3c23b-beb4-450c-b9db-5719dd90f10d

2023-06-29 05:04 UTC, taka392 commented
pushReplacementに変更して修正しました。

2023-06-29 11:28 UTC, iu-yusei commented
下記の導線でRootPageにアクセスすると、スワイプバック機能ができる状態になってしまっています！
- ログインせずに利用するをクリックしたとき
- ログイン直後

https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/78660150/43f46e78-6b57-43cd-aafb-ccecc3e84bbc

2023-06-29 11:29 UTC, taka392 commented
修正します

2023-06-29 12:05 UTC, iu-yusei commented
LGTMです！

2023-06-29 14:13 UTC, ShuheiYoshidaJP commented
auth認証難しいと思いますが、よく実装できていると思います。マージします。

2023-06-29 14:13 UTC, merged