My page
shinonome-inc/mobile_takahiro2_basic_flutter pull request #26
Opened 2023-06-30 03:19 UTC by taka392

## 概要

## CLIENT_IDとCLIENT_SECRET

## 実装した内容

## UI

## 動作確認

## 参考

## その他

2023-06-30 06:25 UTC, iu-yusei commented on qiita_app/lib/models/user_model.dart
変数名が綺麗で読みやすいですし、NullSafetyになっていて、素晴らしいです！

2023-06-30 06:28 UTC, iu-yusei commented on qiita_app/lib/pages/my_page.dart
> +          ? const NoLogin()
NoLoginを別コンポーネントとして切り分けている点、◎です！

2023-06-30 06:33 UTC, iu-yusei commented on qiita_app/lib/pages/my_page.dart
> +  }
try-catch構文、良いですね！

2023-06-30 06:38 UTC, iu-yusei requested changes
ユーザーに紐づいた投稿記事が複数あるとき、
「下までスクロールしても、記事リストが見えない」という状況になっているので、もう少し高さを低くできると良いかもしれません！

※iPhone 14 Plusで検証しています

https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/78660150/2e43b2fc-12f8-4228-9efc-c6bab8c87398

2023-06-30 06:56 UTC, taka392 commented
ユーザーに紐づいた投稿記事が複数あるとき、
「下までスクロールしても、記事リストが見えない」という状況になっているので、もう少し高さを確保できると良いかもしれません！

※iPhone 14 Plusで検証しています
--------------------------
「下までスクロールしても、記事リストが見えない」とは、どういう状況でしょうか？自分の理解力が足りなくてすいません。

2023-06-30 07:57 UTC, iu-yusei commented
説明がわかりにくくてすみません。

[こちら](https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/pull/26#pullrequestreview-1506599023)の動画の５秒あたりから見ていただくとわかるかと思います。

リストを下までスクロールした後、「一瞬、test8という記事が見えてタッチ操作をやめると、すぐに隠れてしまう」という状況になっています！


> ユーザーに紐づいた投稿記事が複数あるとき、 「下までスクロールしても、記事リストが見えない」という状況になっているので、もう少し高さを確保できると良いかもしれません！
> 
> ## ※iPhone 14 Plusで検証しています
> 「下までスクロールしても、記事リストが見えない」とは、どういう状況でしょうか？自分の理解力が足りなくてすいません。

2023-06-30 08:35 UTC, iu-yusei commented
下の画像のように、ListViewの高さを調整できると良いと思います！

![image](https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/78660150/4fea3e06-b6ec-4918-9254-df90ac77c101)

2023-07-01 11:47 UTC, taka392 commented
https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/88756420/2e639b58-3ee9-468b-a86e-c6ae51a2a494

_______________________________________________________________________________
上記は、現在ログインしているユーザに関連する記事一覧を表示するウィジェットの下にContainerを追加しました。pushには含まれていません。

2023-07-01 11:47 UTC, taka392 commented
ListViewの高さを修正しました。

2023-07-01 13:30 UTC, iu-yusei commented
もう少しだけ、高さ調整が必要かもしれません！

<img src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/78660150/993f91ab-467f-4695-a766-f0ffd909b323" width="300">

2023-07-01 13:31 UTC, iu-yusei commented on qiita_app/lib/pages/my_page.dart
> +              height: onRefresh ?MediaQuery.of(context).size.height-468 :MediaQuery.of(context).size.height-418,
MediaQueryで画面サイズを取得できている点、良いですね！

2023-07-01 13:32 UTC, iu-yusei requested changes
もう少しだけ、高さ調整が必要かもしれません！

<img src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/78660150/993f91ab-467f-4695-a766-f0ffd909b323" width="300">

2023-07-01 13:34 UTC, taka392 commented on qiita_app/lib/pages/my_page.dart
> +              height: onRefresh ?MediaQuery.of(context).size.height-468 :MediaQuery.of(context).size.height-418,
ゆうせいちゃん〜見逃してください〜

2023-07-01 13:40 UTC, taka392 commented
記事のタイトルが長さによって1行〜2行に可変してしまうのですが、その場合どうしたら良いでしょうか？

2023-07-01 14:00 UTC, taka392 commented
高さを修正しました

2023-07-01 14:15 UTC, iu-yusei reviewed
LGTMです！
2次レビューに進んでください！

2023-07-01 14:17 UTC, iu-yusei approved these changes

2023-07-02 04:01 UTC, ShuheiYoshidaJP commented on qiita_app/lib/pages/my_page.dart
> +  }
👍

2023-07-02 04:02 UTC, ShuheiYoshidaJP commented
オッケーです。マージします。

2023-07-02 04:02 UTC, merged