Final ajustment
shinonome-inc/mobile_takahiro2_basic_flutter pull request #35
Opened 2023-09-19 00:05 UTC by taka392

## 概要
(#33 )の内容を修正しました。

## CLIENT_IDとCLIENT_SECRET
[こちら](https://drive.google.com/drive/folders/1NXfoWztNBH0_iZYZeLLhQB11I2blq5-z?usp=sharing)から、クライアントIDをダウンロードしてください.

## 実装した内容
pubspec.yamlに.envの追加
ローディングのモーダルのタイトルをarticleに変更
Setting Page
ーIncorrect use of ParentDataWidgetの修正
ーアプリ情報のPaddingの修正
ーー文字の太さ
ーー区切り線
ーーアプリケーションバージョン→アプリバージョン
flutter_web_viewのアップデート
fvmの導入
検索ワードがHintTextに保存されるように修正
選択/非選択時の文字サイズを固定
Feed Page
ーユーザーIDと登校日といいねの間に半角スペースの追加
ー検索結果がない場合の画面が一瞬表示される誤作動の修正
Setting Page
ーログアウトボタンが一瞬表示される誤作動の修正

2023-09-22 02:53 UTC, KobayashiYoh commented
プルリクにissueのリンクが貼ってある点や実装内容の一覧が記載されている点に関して、一目で実装の内容が伝わってきて非常に良いと思いました。
今回はUIに変更が多くあるので、面倒かもしれませんが、シュミレータのスクショを貼っておくと更に情報が伝わりやすいプルリクになると思います👍

2023-09-22 05:59 UTC, KobayashiYoh requested changes
3点コメントしました。

2023-09-22 05:59 UTC, KobayashiYoh commented on qiita_app/lib/components/search_app_bar.dart
>    }) : super(key: key);
表示されたwarningやinfoに対してignoreするよりも、warningやinfoの指示に従って修正できた方がいいかもしれませんね。
例えば、この箇所だとignoreを使わずに以下のように修正することができます。

```dart
import 'package:flutter/material.dart';

class SearchAppBar extends StatelessWidget implements PreferredSizeWidget {
  final Function(String) onArticlesChanged;
  final String searchWord;
  final TextEditingController _textEditingController = TextEditingController();

  SearchAppBar({
    Key? key,
    required this.onArticlesChanged,
    required this.searchWord,
  }) : super(key: key);
```

2023-09-22 05:59 UTC, KobayashiYoh commented on qiita_app/lib/components/search_app_bar.dart
> +                hintText: searchWord,
入力した文字列がhintTextになっちゃっていますね。
hintTextはFigmaと同じ`Search`のままでお願いします。

https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82624334/7f8ccb7b-34ab-4755-ac95-706d10f57fc9

2023-09-22 05:59 UTC, KobayashiYoh commented on qiita_app/lib/services/repository.dart
> +          'https://qiita.com/api/v2/items?page=$page&per_page=20&query=body:$searchWord'));
これだと60回以上リクエストできないのでログイン時はリクエストにアクセストークンを含めましょう。

2023-09-23 09:04 UTC, taka392 commented on qiita_app/lib/components/search_app_bar.dart
>    }) : super(key: key);
searchWordにfinalを追加して修正しました

2023-09-23 10:27 UTC, taka392 commented on qiita_app/lib/components/search_app_bar.dart
> +                hintText: searchWord,
HintTextをSearchのままの状態に修正しました

2023-09-23 13:53 UTC, taka392 commented on qiita_app/lib/services/repository.dart
> +          'https://qiita.com/api/v2/items?page=$page&per_page=20&query=body:$searchWord'));
アクセストークンキーがシェアードプリファレンスに保存されている時、ヘッダーにアクセストークンを付与さるように修正しました。

2023-09-24 06:05 UTC, KobayashiYoh commented on qiita_app/lib/components/search_app_bar.dart
>    }) : super(key: key);
OKです👍

2023-09-24 06:05 UTC, KobayashiYoh commented on qiita_app/lib/components/search_app_bar.dart
> +                hintText: searchWord,
OKです👍

2023-09-24 06:08 UTC, KobayashiYoh commented
https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/issues/33 
こちらに関する修正もお願いします。

2023-09-26 08:56 UTC, KobayashiYoh commented
修正確認しました👍

https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/issues/33#issuecomment-1730909261 
最後に、こちらのエラー関連の修正だけお願いします。
ラストスパートです🔥

2023-09-27 10:12 UTC, KobayashiYoh commented on qiita_app/lib/services/repository.dart
> +          'https://qiita.com/api/v2/items?page=$page&per_page=20&query=body:$searchWord'));
OKです👍

2023-09-27 10:42 UTC, KobayashiYoh commented
## マイページについて
### 1. ユーザーの投稿記事が表示されない
ユーザーが投稿した記事が表示されていないので修正お願いします。
みんながつまづきやすいpull to refreshに関してはよくできていて素晴らしいです👍
<img src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82624334/9452259f-7edb-46f1-ae7a-419738067d54" width="300">

### 2. MyPageでエラー時にAppBarのタイトルが表示されない
MyPageでエラー時にもAppBarのタイトルを表示するように修正お願いします。
FeedPageではしっかり修正できています。
<img src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82624334/bdb9ef2d-7108-4bf7-a27c-e4cf8e06e4b4" width="300">

### 3. MyPageで再読み込みによるエラー復帰ができない
インターネット接続をオンからオフに戻した後、リロードするとユーザー情報が表示されず、本来画面に表示されるべきではないエラーの文字列が表示されてしまっています。
修正お願いします。

https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82624334/fec461ab-b7f8-410d-b25d-4cbc5f3f6d89

2023-09-27 11:11 UTC, taka392 commented
あぱ〜

2023-09-27 11:16 UTC, KobayashiYoh commented
一応、仕様テストでも確認はされたと思うのですが、結構漏れが多いので、作成したアプリのUIや要件を満たしているかご確認お願いします。
UIや仕様が異なっている場合は修正をお願いしています。

また、自分がアプリを使うユーザーになったつもりで実装したアプリを触ってみてください。
そうするだけでも不具合の早期発見に繋がり、アプリの品質が大きく向上すると思います。

2023-12-05 08:41 UTC, taka392 commented
1. ユーザーの投稿記事が表示されない
を修正しました
![ユーザー投稿記事](https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/88756420/579f518d-b198-4454-bd3b-b7f3ba49bf8d)

2023-12-05 09:00 UTC, taka392 commented
３.MyPageで再読み込みによるエラー復帰ができない
を修正しました


https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/88756420/55298575-85ab-41d2-94c7-8478e0e884ab

2023-12-05 10:07 UTC, taka392 commented
2. MyPageでエラー時にAppBarのタイトルが表示されない
Figmaはネットワーク時にAppbarにタイトルが表示されていなかったので、Figmaに合わせました。
<img width="379" alt="ネット" src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/88756420/2fe35695-b681-4290-b07c-8ae282d2e432">

2023-12-05 13:44 UTC, KobayashiYoh approved these changes
今後参加する案件などでも自分の実装が要件を満たしているか、Figmaのデザイン通りにUIが組めているかどうかを確認しておくとさらにレベルアップできると思います！！
長い修正でしたが、超超超お疲れ様でした！

コース修了おめでとう🎉

2023-12-05 13:44 UTC, merged